// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/thegodev/google-wire-demo/greeter"
	"github.com/thegodev/google-wire-demo/message"
)

// Injectors from wire.go:

// initializeApp creates an app with wire to inject all of the dependencies
func initializeApp(phrase string) (app, error) {
	messageMessage := message.ProvideMessage(phrase)
	greeterGreeter := greeter.ProvideGreeter(messageMessage)
	mainApp, err := provideApp(greeterGreeter)
	if err != nil {
		return app{}, err
	}
	return mainApp, nil
}
