// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/camerontrew/DI-Test/greeter"
	"github.com/camerontrew/DI-Test/message"
)

// Injectors from wire.go:

// InitializeEvent creates an Event. It will error if the Event is staffed with
// a grumpy greeter.
func initializeApp(phrase string) (app, error) {
	messageMessage := message.ProvideMessage(phrase)
	greeterGreeter := greeter.ProvideGreeter(messageMessage)
	mainApp, err := provideApp(greeterGreeter)
	if err != nil {
		return app{}, err
	}
	return mainApp, nil
}
